version: '3'
services:
    vue:
        build: ./vue
        ports:
            - "2222:22"
        volumes:
            - ./vue:/root/app
        stdin_open: true
        tty: true

    nginx:
        build: ./nginx
        ports:
            - 8080:80
            - 8081:81
        volumes:
            - "./vue/dist:/var/www/html/public"
            - "./php:/var/www/html/"
            - "./nginx/log:/var/log/nginx"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

    php:
        build: ./php
        volumes:
            - "./php:/var/www/html/"
